title: Zohaib Khan
logo: /assets/img/logo.png
description: GCP - PCA | CKA | CKAD | DevOps | SRE | CI/CD | Kafka | Terraform | Ansible | Puppet | GCP | AWS | Cloudera BigData & Hadoop
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal